import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/123.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svg/1.png"
import TransitionEffect from '@/components/TransitionEffect'


export default function Home() {
  return (
  <>
      <Head>
          <title>PT KSN</title>
          <meta name="description" content="Generated by create next app"/>
      </Head>
      <TransitionEffect/>
        <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout classname='pt-0 md:p-16 sm:pt-8'>
          <div class="flex items-center justify-between w-full lg:flex-col">
          <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark
            bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8
            '>
                <div className='absolute top-0 -right-4 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light'/>
                <Image src={profilePic} alt="HadiRamadhan" className="w-full h-auto rounded-2xl"
                priority
                sizes='(max-width: 768px) 100vw,
                (max-width: 1200px 50vw),
                33vw
                '
                />
            </div>
              <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
                <AnimatedText text="Aura Syifa Almira" className='!text-6xl xl:text-5xl 
                lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl
                '/>
                <p className='text-center text-bold text-2xl md:text-sm sm:text-xs'>
                  Pt Komoditas Sinergi Nusantara
                </p>
                <div className='flex items-center self-center mt-2 lg:self-center'>
                  <Link href="https://wa.me/621213445526" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2,5 px-3 rounded-lg text-lg font-bold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark

                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light md:p-2 md:px-2 md:text-base
                  '
                  download={true}
                  >Tanya Kami <LinkArrow className={"absoloute w-2 ml-2 pb-2 top-0"}/>
                  </Link>
                  <Link href="mailto:Aurasyifaalmira@gmail.com" target={"_blank"}
                  className='ml-4 text-md font-medium capitalize text-dark underline dark:text-light md:text-base'
                  >Contact Kami</Link>
                </div>
              </div>
          </div>
        </Layout>
        {/* <HireMe/> */}
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden ' >
          {/* <Image src={lightBulb} alt='HadiRamadhan' className='w-full h-auto'/> */}
        </div>
    </main>
    </>
    
  )
}
